---
  - name: "Instala o apache em distro derivadas do Debian"
    apt:
      name:
        - apache2
        - libapache2-mod-fcgid
        - libapache2-mod-security2
        - libapache2-mod-evasive
        - openssl
      state: latest
    when: (ansible_facts['os_family'] == "Debian")
    notify: 
      - enableApache2

  - name: "Habilita mods do apache2 - Debian"    
    apache2_module:
      name: "{{ item }}"
    with_items:
      - actions
      - fcgid
      - alias
      - proxy_fcgi
      - headers
      - ssl
    when: (ansible_facts['os_family'] == "Debian")
