---
- name: "instala o Apache em distro derivadas do RedHat"
  yum: 
    name:
      - httpd
      - openssl
  state: latest
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - enableHttpd

- name: "CriaDirVhostRedHat"
  file:
    path: "/etc/httpd/vhost.d"
    state: directory
  when: (ansible_facts['os_family'] == "RedHat")

- name: "Cria virtual hosts com as configuracoes do site - RedHat"
  template:
    src: templates/site.conf
    dest: /etc/http/vhost.d/{{ log_prefix }}.conf
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - addInHostsFile
    - addInHttpdFile
    - RestartHttpd
    - InstallWordpress
    - SetPermissionWP-CentOS    